import {
  ROLES,
} from './roles.js'

import {
  PERMISSIONS,
} from './permissions.js'

export const ROLE_PERMISSIONS = {

  [ROLES.SUPERADMIN]: [
    ...Object.values(
      PERMISSIONS
    ),
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.CHANGE_USER_ROLE,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.MANAGE_MESAS,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.MANAGE_TICKETS,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.MANAGE_MESAS,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.MANAGE_TICKETS,
  ],

  [ROLES.EMPLOYEE]: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_MESAS,
    PERMISSIONS.MANAGE_TICKETS,
  ],

  [ROLES.CUSTOMER]: [],

}